version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.8.5
  macos:
    macos:
      xcode: "12.0.0"
    environment:
      LANG: "en_US.UTF-8"
      HOMEBREW_NO_AUTO_UPDATE: "1"
      HOMEBREW_NO_INSTALL_CLEANUP: "1"

commands:
  run_sym_script:
    steps:
      - run:
          name: Run sym installer
          command: |
            cat ~/project/docs/sym.sh | bash -x
            export PATH="$HOME/.local/bin:$PATH"
            sym version
  run_symflow_script:
    steps:
      - run:
          name: Run symflow installer
          command: |
            cat ~/project/docs/symflow.sh | bash -x
            export PATH="$HOME/.local/bin:$PATH"
            symflow version
  test_sym_formula:
    steps:
      - run:
          name: Test sym Formula
          command: |
            brew install --formula ~/project/Formula/sym.rb
            sym version
  test_symflow_formula:
    steps:
      - run:
          name: Test symflow Formula
          command: |
            brew install --formula ~/project/Formula/symflow.rb
            symflow version

jobs:
  test_install_script:
    parameters:
      executor:
        type: string
    executor:
      name: << parameters.executor >>
    steps:
      - checkout:
          path: ~/project
      - run_sym_script
      - run_symflow_script
  test_formulas:
    executor:
      name: macos
    steps:
      - checkout:
          path: ~/project
      - test_sym_formula
      - test_symflow_formula

workflows:
  test:
    jobs:
      # Test comment
      - test_install_script:
          matrix:
            parameters:
              executor: ["macos", "python"]
      - test_formulas
