name: brew test-bot
on:
  push:
    branches: master
  pull_request: []
jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run brew test-bot
        env:
          HOMEBREW_BINTRAY_USER: ${{secrets.HOMEBREW_BINTRAY_USER}}
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        run: |
          set -e
          brew update
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/symopsio/homebrew-tap"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"
          ln -s "$PWD" "$HOMEBREW_TAP_DIR"
          ./scripts/bottles.sh
      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
